### ISSUE TITLE
Crash on Mojave upon installing

### ISSUE THREAD

**Issue by lukka5** [bacongravy/giphy-anywhere#4]
After installing cask this message appears:

    Error on line 6: Error: An error occurred. (-1743)

Tried re-installing with the same result.

**Comment by bacongravy** [comment]
Hello, @lukka5! Thank you for the report. I'm sorry that this application is not working on Mojave; the issue you are reporting sounds sounds similar to #3.

I suspect that I will have to rewrite this tool to use a different technology besides JXA to get this working again on Mojave.

**Comment by bacongravy** [comment]
I've pushed up a [`swift`](https://github.com/bacongravy/giphy-anywhere/tree/swift) branch with the app re-implemented in Swift 4. I've gotten everything working except for managing the LoginItem.

**Comment by bacongravy** [comment]
I've rewritten the app to work on Mojave but I haven't updated the installation instructions. The old [bacongravy/jxa/giphy-anywhere](https://github.com/bacongravy/homebrew-jxa/blob/master/Casks/giphy-anywhere.rb) cask no longer works. I'm going to leave this issue open until I've gotten everything working again.

**Comment by bacongravy** [comment]
Hi again, @lukka5!  You should be able to get up and running by running the following commands:

    brew cask uninstall giphy-anywhere
    brew untap bacongravy/jxa
    brew cask install bacongravy/tap/giphy-anywhere

Let me know if you have any problems.
